## load data & EDA

In [6]:
# Data
import pandas as pd
import numpy as np

# Hugging Face Dataset
from datasets import load_dataset

# Train/Test Split
from sklearn.model_selection import train_test_split

# Label Encoding
from sklearn.preprocessing import LabelEncoder

# Metrics
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Plotting
import matplotlib.pyplot as plt
import seaborn as sns

# Hugging Face
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    TrainingArguments,
    Trainer
)

# Torch
import torch

from langchain_huggingface import HuggingFaceEndpoint

from huggingface_hub import login

In [7]:
from datasets import load_dataset
dataset = load_dataset("ag_news")

README.md: 0.00B [00:00, ?B/s]

C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lenovo\.cache\huggingface\hub\datasets--ag_news. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/train-00000-of-00001.parquet:   0%|          | 0.00/18.6M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/120000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/7600 [00:00<?, ? examples/s]

In [8]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 120000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 7600
    })
})

In [9]:
train_df = dataset["train"].to_pandas()
test_df = dataset["test"].to_pandas()

In [10]:
train_df.head()

                                                text  label
0  Wall St. Bears Claw Back Into the Black (Reute...      2
1  Carlyle Looks Toward Commercial Aerospace (Reu...      2
2  Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3  Iraq Halts Oil Exports from Main Southern Pipe...      2
4  Oil prices soar to all-time record, posing new...      2

In [15]:
labels = dataset["train"].features["label"].names
print(labels)

['World', 'Sports', 'Business', 'Sci/Tech']

In [12]:
df = pd.concat([
    dataset["train"].to_pandas(),
    dataset["test"].to_pandas()
], ignore_index=True)

In [13]:
df

                                                     text  label
0       Wall St. Bears Claw Back Into the Black (Reute...      2
1       Carlyle Looks Toward Commercial Aerospace (Reu...      2
2       Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3       Iraq Halts Oil Exports from Main Southern Pipe...      2
4       Oil prices soar to all-time record, posing new...      2
...                                                   ...    ...
127595  Around the world Ukrainian presidential candid...      0
127596  Void is filled with Clement With the supply of...      1
127597  Martinez leaves bitter Like Roger Clemens did ...      1
127598  5 of arthritis patients in Singapore take Bext...      2
127599  EBay gets into rentals EBay plans to buy the a...      2

[127600 rows x 2 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127600 entries, 0 to 127599
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   text    127600 non-null  object
 1   label   127600 non-null  int64
dtypes: int64(1), object(1)
memory usage: 1.9+ MB

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.isnull().sum()

text     0
label    0
dtype: int64

In [18]:
df["label"].value_counts()

label
2    31900
3    31900
1    31900
0    31900
Name: count, dtype: int64

## preprocessing

In [19]:
df["text"]=df["text"].str.strip()

In [20]:
from transformers import DistilBertTokenizerFast
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

encoded = tokenizer(
    df["text"].tolist(),
    truncation=True,
    padding=True
)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lenovo\.cache\huggingface\hub\models--distilbert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]